version: '3'

services:

  app:
    container_name: products-frontend
    build: .
    command: runserver
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8501/health/"]
      interval: 10s
      timeout: 10s
      retries: 3


